version: "3.3"
services:
  master:
    build: ./master
    image: moditamam/jenkins-master
    networks:
      - bridge
    privileged: true
    ports:
    - "80:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
    - jenkins-master:/var/jenkins_home

  worker:
    image: moditamam/jenkins-agent:docker-inside
    networks:
      - bridge
    build: ./agent
    privileged: true
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8080"
      JENKINS_NAME: "worker"
      JENKINS_USER: "admin"
      JENKINS_PASS: "1234"
      JENKINS_RETRY: "10"
      JENKINS_LABELS: "agent_1"
    volumes:
    - jenkins-worker:/var/jenkins_home/worker
    - /var/run/docker.sock:/var/run/docker.sock
    - $HOME:/external

volumes:
  jenkins-master:
  jenkins-worker:
networks:
  bridge: